### ISSUE TITLE
代码不完整吗？

### ISSUE THREAD

**Issue by AzulYang** [Yuqifan1117/Annotation-anything-pipeline#2]
load AIGC models for generation
```
from diffusers import StableDiffusionPipeline
from diffusers import StableDiffusionInpaintPipeline
```
initialize the annotation pipeline.
`bash grounded_sam.sh`

没有grounded_sam.sh这个文件，还有这个load AIGC模块放在哪？

**Comment by Yuqifan1117** [comment]
Thank you for your question. We are very sorry for the unclear explanation before. We have updated the name (`grounded_sam.sh` -> `annotation.sh`), and the AIGC model loading is called in `grounded_edit.py`

**Comment by AzulYang** [comment]
I successfully ran it using CPU before, and now I want to use it to complete some instance segmentation tasks. However, due to the slow CPU speed, I tried using CUDA, but encountered some problems. Firstly, there was an "_C" error in GroundingDINO, which I have resolved, But later on, I encountered: _**CUDA error: no kernel image is available for execution on the devic**_e. After checking the data online, I found that it was a mismatch in computing power between PyTorch and CUDA. My current configuration is as follows: PyTorch 2.0.0, CUDA 11.7, GPU 3060, GPU computing power is 8.6, I set it to 8.0 in the environment variable or it displayed an error. Have you ever encountered this problem? Can you give me some advice.THanks a lot. @Yuqifan1117

**Comment by Yuqifan1117** [comment]
I think this is due to a torch version issue. I was using torch 1.8+cu113, so you can try this configuration. Meanwhile, building the setup.py environment under GroundingDINO, if it can be passed, seems to solve the problems you have.

**Comment by AzulYang** [comment]
Is this script:"conda install pytorch==1.8.1 torchvision==0.9.1 torchaudio==0.8.1 cudatoolkit=11.3 -c pytorch -c conda-forge" right?And can you explain the specific version of Python.Will the Python version have an impact on some dependencies?

**Comment by AzulYang** [comment]
I rechecked GroundDINO and found an updated environment.yaml, which provided torch 2.0.1+cu118. In addition, I still reported an error during testing on torch 1.8.0+cu111

**Comment by Yuqifan1117** [comment]
I have already reproduced this project within the environment (python 3.8, torch==1.10.0+cu113) on the 3090. There is no problem. I think your problem should be that the computing power of 3060 doesn't match the high version of CUDA. You can reduce the CUDA version and compile on the corresponding torch version, which would solve your problem.
