### ISSUE TITLE
Problems in run grounded_sam.py in my dataset and label 'car'

### ISSUE THREAD

**Issue by AzulYang** [Yuqifan1117/Annotation-anything-pipeline#4]
When I run the command, I download _pytorch_ model.bin_。
![ADKKW38PNGKB9DME7TTWPCC](https://user-images.githubusercontent.com/105103450/232690002-a3d3c8d7-a697-4c75-924b-86ec366adf82.png)
Due to the slow speed and multiple failures, I searched for the Bert pre trained model, which can be downloaded locally and imported into the _groundingdino.py_,  but I am not sure if this thought is correct. If possible, could you please add my QQ: 343978442

**Comment by AzulYang** [comment]
While bert-base-uncased is already downloaded completely,and I have no idea about downloading another 1.88G pytorch_model.bin,what is that?

**Comment by Yuqifan1117** [comment]
In grounding_sam.py, we also need the model of BLIP to get initial captions and another 1.88G pytorch_model.bin is the model of BLIP from huggingface. You can download and import them manually.
